'use client';

import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { ChevronDown, ChevronUp, ShieldCheck } from 'lucide-react';
import { BRAND, CONTACT } from '@/lib/constants';

const sections = [
  {
    title: '1. Information We Collect',
    content: `We collect information you provide directly to us (name, email, phone, location, payment details), information generated by your use of the platform (booking history, messages, reviews), and technical data (IP address, browser type, device information, cookies). Location data is only collected with your explicit permission.`,
  },
  {
    title: '2. How We Use Your Information',
    content: `Your data is used to: (a) provide and improve our services, (b) match clients with appropriate providers, (c) process payments and resolve disputes, (d) send transactional emails and notifications, (e) prevent fraud and ensure platform safety, and (f) comply with legal obligations. We do not sell your personal data to third parties.`,
  },
  {
    title: '3. Information Sharing',
    content: `We share your information with: service providers needed to deliver your booking (e.g., providers see your contact info after booking confirmation), payment processors (Stripe, bKash) operating under strict data agreements, law enforcement when required by law, and business partners with your explicit consent. We maintain strict contracts with all third parties requiring data protection.`,
  },
  {
    title: '4. Data Retention',
    content: `We retain your account data for as long as your account is active. Booking records are kept for 7 years for legal and tax compliance. You may request deletion of your account at any time, after which your personal data will be anonymized within 30 days, except where retention is legally required.`,
  },
  {
    title: '5. Cookies & Tracking',
    content: `We use essential cookies (required for the platform to function), analytics cookies (to understand usage patterns and improve the product), and preference cookies (to remember your settings). You can control non-essential cookies via our cookie preferences center. We do not use cross-site tracking cookies.`,
  },
  {
    title: '6. Your Rights',
    content: `You have the right to: access the personal data we hold about you, correct inaccurate data, request deletion of your data ("right to be forgotten"), restrict or object to certain processing, receive your data in a portable format, and withdraw consent at any time where processing is consent-based. To exercise any right, email ${CONTACT.email}.`,
  },
  {
    title: '7. Data Security',
    content: `We implement industry-standard security measures including TLS encryption for all data in transit, AES-256 encryption for sensitive data at rest, regular security audits and penetration testing, and strict access controls with 2FA for all staff. However, no system is 100% secure — we encourage strong passwords and prompt reporting of suspicious activity.`,
  },
  {
    title: '8. Children\'s Privacy',
    content: `${BRAND.name} is not directed to children under 18. We do not knowingly collect personal data from minors. If we discover that a child under 18 has provided us with personal information, we will delete it immediately. Parents or guardians who believe their child's data has been collected should contact us immediately.`,
  },
  {
    title: '9. International Data Transfers',
    content: `Your data may be processed in servers located outside Bangladesh, including within the EU and US. We ensure all international transfers comply with applicable data protection laws and that recipient countries or organizations provide an adequate level of data protection.`,
  },
  {
    title: '10. Changes to This Policy',
    content: `We may update this Privacy Policy periodically to reflect changes in our practices or applicable laws. We will notify you of material changes via email or a prominent notice on our platform at least 30 days before the change takes effect. We encourage you to review this page regularly.`,
  },
];

function Section({ title, content }: { title: string; content: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`rounded-[1.5rem] border transition-all ${open ? 'border-[#2286BE]/30 bg-white shadow-lg shadow-[#2286BE]/5' : 'border-slate-100 bg-white'}`}>
      <button onClick={() => setOpen(!open)} className="w-full flex items-center justify-between gap-4 p-7 text-left">
        <span className="font-black text-slate-900 text-lg">{title}</span>
        {open ? <ChevronUp size={20} className="text-[#2286BE] shrink-0" /> : <ChevronDown size={20} className="text-slate-400 shrink-0" />}
      </button>
      {open && <div className="px-7 pb-7"><p className="text-slate-600 font-medium leading-relaxed">{content}</p></div>}
    </div>
  );
}

export default function PrivacyClient() {
  return (
    <div className="min-h-screen bg-[#F8FAFC]">

      {/* Hero */}
      <section className="bg-slate-900 pt-24 pb-20 text-center relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-[#2286BE]/10 rounded-full translate-x-1/2 -translate-y-1/2 blur-[100px] pointer-events-none" aria-hidden="true" />
        <div className="relative z-10 max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <span className="inline-flex bg-[#2286BE]/20 text-[#2286BE] px-4 py-2 rounded-full font-black text-xs uppercase tracking-widest mb-6">Legal</span>
            <h1 className="text-5xl font-black text-white tracking-tight mb-4 mt-4">Privacy Policy</h1>
            <p className="text-slate-400 font-medium">Last updated: March 28, 2026</p>
          </motion.div>
        </div>
      </section>

      {/* Trust Banner */}
      <section className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}
          className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-12">
          {[
            { title: 'No Data Selling', desc: `We never sell your personal data to third parties.` },
            { title: 'Encrypted Storage', desc: 'All sensitive data is encrypted at rest and in transit.' },
            { title: 'Your Control', desc: 'You can request data deletion at any time.' },
          ].map(item => (
            <div key={item.title} className="bg-white rounded-[1.5rem] border border-slate-100 p-6 flex gap-4">
              <ShieldCheck size={22} className="text-[#2286BE] shrink-0 mt-0.5" />
              <div>
                <p className="font-black text-slate-900 mb-1">{item.title}</p>
                <p className="text-sm font-medium text-slate-500">{item.desc}</p>
              </div>
            </div>
          ))}
        </motion.div>

        <div className="bg-[#2286BE]/5 border border-[#2286BE]/20 rounded-[1.5rem] p-8 mb-10">
          <p className="text-[#2286BE] font-bold leading-relaxed">
            Your privacy is important to us. This policy explains what data we collect, why we collect it, how we use it, and what rights you have over it. We are committed to transparency and giving you meaningful control over your personal information at {BRAND.name}.
          </p>
        </div>

        <div className="space-y-4">
          {sections.map((sec, i) => (
            <motion.div key={sec.title} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.04 }}>
              <Section {...sec} />
            </motion.div>
          ))}
        </div>

        <div className="mt-12 bg-white rounded-[1.5rem] border border-slate-100 p-8 text-center">
          <p className="text-slate-500 font-medium">Privacy questions? Email us at <a href={`mailto:${CONTACT.email}`} className="text-[#2286BE] font-black hover:underline">{CONTACT.email}</a></p>
        </div>
      </section>

    </div>
  );
}
