const DEFAULT_CATEGORIES = [
  {
    name: "LocallyServe Pro",
    slug: "locallyserve-pro",
    iconName: "ShieldCheck",
    description: "Exclusive premium services provided directly by LocallyServe. Guaranteed quality, priority support, and in-house fully vetted professionals.",
    color: "bg-indigo-100 text-indigo-600",
    bgGradient: "from-indigo-100 to-white",
  },
  {
    name: "Cleaning",
    slug: "cleaning",
    iconName: "Droplets",
    description: "Professional home and office cleaning services from verified experts in your neighborhood.",
    color: "bg-blue-50 text-blue-500",
    bgGradient: "from-blue-50 to-white",
  },
  {
    name: "Plumbing",
    slug: "plumbing",
    iconName: "Wrench",
    description: "Fast and reliable plumbing repairs, installations, and maintenance from certified professionals.",
    color: "bg-orange-50 text-orange-500",
    bgGradient: "from-orange-50 to-white",
  },
  {
    name: "Electrical",
    slug: "electrical",
    iconName: "Zap",
    description: "Certified electricians for safe wiring, installations, repairs, and panel upgrades.",
    color: "bg-yellow-50 text-yellow-500",
    bgGradient: "from-yellow-50 to-white",
  },
  {
    name: "Painting",
    slug: "painting",
    iconName: "Paintbrush",
    description: "Interior and exterior painting services to transform your home with expert brush strokes.",
    color: "bg-pink-50 text-pink-500",
    bgGradient: "from-pink-50 to-white",
  },
  {
    name: "Pest Control",
    slug: "pest-control",
    iconName: "Trash2",
    description: "Safe, effective pest elimination and prevention treatments by certified pest control experts.",
    color: "bg-green-50 text-green-500",
    bgGradient: "from-green-50 to-white",
  },
  {
    name: "Appliance Repair",
    slug: "appliance-repair",
    iconName: "Cpu",
    description: "Expert repair and maintenance of home appliances from ACs to washing machines.",
    color: "bg-indigo-50 text-indigo-500",
    bgGradient: "from-indigo-50 to-white",
  },
  {
    name: "Carpentry",
    slug: "carpentry",
    iconName: "Hammer",
    description: "Skilled carpenters for furniture repair, custom builds, and home woodwork projects.",
    color: "bg-amber-50 text-amber-500",
    bgGradient: "from-amber-50 to-white",
  },
  {
    name: "Shipping",
    slug: "shipping",
    iconName: "Truck",
    description: "Safe and efficient home and office moving services with professional movers.",
    color: "bg-purple-50 text-purple-500",
    bgGradient: "from-purple-50 to-white",
  },
  {
    name: "Beauty",
    slug: "beauty",
    iconName: "Scissors",
    description: "On-demand beauty and grooming professionals who come straight to your door.",
    color: "bg-rose-50 text-rose-500",
    bgGradient: "from-rose-50 to-white",
  },
  {
    name: "Personal Care",
    slug: "personal-care",
    iconName: "Heart",
    description: "Compassionate caregivers and personal care assistants for all ages and needs.",
    color: "bg-red-50 text-red-500",
    bgGradient: "from-red-50 to-white",
  },
];

module.exports = {
  DEFAULT_CATEGORIES,
};
